import sys

filepath = 'C:/Users/baenb/projects/project _cameron/aicomplydocs/src/lib/regulation-config.ts'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

new_configs = (
    '  "virginia-cdpa": {\n'
    '    name: "Virginia CDPA",\n'
    '    statute: "Va. Code \u00a7\u00a7 59.1-575\u201359.1-584",\n'
    '    lawUrl: "https://law.lis.virginia.gov/vacodefull/title59.1/chapter53/",\n'
    '    lawLinkText: "Read Va. Code \u00a7\u00a7 59.1-575 through 59.1-584 on law.lis.virginia.gov",\n'
    '    acknowledgment:\n'
    '      "I have reviewed Va. Code \u00a7\u00a7 59.1-575 through 59.1-584 (Virginia Consumer Data Protection Act) and understand that these are compliance templates, not legal advice. The VCDPA has been in effect since January 1, 2023. I should verify the current regulatory status and consult qualified legal counsel.",\n'
    '    basePrice: 249,\n'
    '    trainingKitAvailable: false,\n'
    '    trainingKitPrice: 0,\n'
    '    documents: [\n'
    '      "Privacy Notice Template",\n'
    '      "Data Protection Assessment",\n'
    '      "Consumer Rights Request Procedures",\n'
    '      "Opt-Out Documentation",\n'
    '      "Data Processing Agreement Template",\n'
    '      "Compliance Checklist",\n'
    '    ],\n'
    '    decisions: [\n'
    '      ["profiling", "Profiling/Automated Decisions"],\n'
    '      ["targeted_ads", "Targeted Advertising"],\n'
    '      ["data_sales", "Data Sales"],\n'
    '      ["sensitive_data", "Sensitive Data Processing"],\n'
    '    ],\n'
    '    helpTexts: {\n'
    '      step2Help:\n'
    '        "<strong>What AI systems are covered?</strong> Any system that uses personal data of Virginia consumers for profiling, targeted advertising, data sales, or processing sensitive data. If your AI system makes decisions about consumers that produce legal or similarly significant effects \u2014 include it.",\n'
    '      step2Intro:\n'
    '        "List each AI or data processing system used in activities covered by the Virginia Consumer Data Protection Act.",\n'
    '      step2DecisionHelp:\n'
    '        "Check every category where this system processes Virginia consumer data. The Virginia CDPA covers profiling for consequential decisions, targeted advertising, data sales, and sensitive data processing.",\n'
    '      step2MultiHelp:\n'
    '        "If you use multiple systems across these categories, list each separately. Each may require its own data protection assessment.",\n'
    '      step3BiasHelp:\n'
    '        "If your system uses profiling to make decisions with legal or similarly significant effects, a bias review helps document that your processing is conducted with reasonable care and does not produce disparate impact.",\n'
    '      step4Help:\n'
    '        "This section captures your oversight and governance for data processing activities. Virginia law requires responding to consumer rights requests within 45 days and providing an appeals mechanism for denied requests (\u00a7 59.1-578(B)).",\n'
    '      step5Intro:\n'
    '        "This contact will be listed in your privacy notices and consumer rights procedures as the designated privacy contact under the Virginia CDPA.",\n'
    '    },\n'
    '  },\n'
    '  "connecticut-ctdpa": {\n'
    '    name: "Connecticut CTDPA",\n'
    '    statute: "Conn. Gen. Stat. \u00a7\u00a7 42-515\u201342-525",\n'
    '    lawUrl: "https://www.cga.ct.gov/current/pub/chap_743jj.htm",\n'
    '    lawLinkText: "Read Conn. Gen. Stat. \u00a7\u00a7 42-515 through 42-525 on cga.ct.gov",\n'
    '    acknowledgment:\n'
    '      "I have reviewed Conn. Gen. Stat. \u00a7\u00a7 42-515 through 42-525 (Connecticut Data Privacy Act, PA 22-15) and understand that these are compliance templates, not legal advice. The CTDPA has been in effect since July 1, 2023, and the mandatory cure period has expired. I should verify the current regulatory status and consult qualified legal counsel.",\n'
    '    basePrice: 249,\n'
    '    trainingKitAvailable: false,\n'
    '    trainingKitPrice: 0,\n'
    '    documents: [\n'
    '      "Privacy Notice Template",\n'
    '      "Data Protection Assessment",\n'
    '      "Consumer Rights Request Procedures",\n'
    '      "Profiling Opt-Out Documentation",\n'
    '      "Data Processing Agreement Template",\n'
    '      "Compliance Checklist",\n'
    '    ],\n'
    '    decisions: [\n'
    '      ["profiling", "Profiling/Automated Decisions"],\n'
    '      ["targeted_ads", "Targeted Advertising"],\n'
    '      ["data_sales", "Data Sales"],\n'
    '      ["sensitive_data", "Sensitive Data Processing"],\n'
    '    ],\n'
    '    helpTexts: {\n'
    '      step2Help:\n'
    '        "<strong>What AI systems are covered?</strong> Any system that uses personal data of Connecticut consumers for profiling, targeted advertising, data sales, or processing sensitive data. If your AI system makes decisions about consumers that produce legal or similarly significant effects \u2014 include it.",\n'
    '      step2Intro:\n'
    '        "List each AI or data processing system used in activities covered by the Connecticut Data Privacy Act.",\n'
    '      step2DecisionHelp:\n'
    '        "Check every category where this system processes Connecticut consumer data. The CTDPA covers profiling for consequential decisions, targeted advertising, data sales, and sensitive data.",\n'
    '      step2MultiHelp:\n'
    '        "If you use multiple systems across these categories, list each separately. Each may require its own data protection assessment.",\n'
    '      step3BiasHelp:\n'
    '        "If your system uses profiling to make consequential decisions, a bias review helps document that your processing is conducted with reasonable care and does not produce discriminatory impact.",\n'
    '      step4Help:\n'
    '        "This section captures your oversight and governance for data processing activities. Connecticut law requires responding to consumer rights requests within 45 days. The mandatory 60-day cure period expired December 31, 2024 \u2014 compliance is now expected immediately.",\n'
    '      step5Intro:\n'
    '        "This contact will be listed in your privacy notices and consumer rights procedures as the designated privacy contact under the Connecticut CTDPA.",\n'
    '    },\n'
    '  },\n'
    '  "oregon-cpa": {\n'
    '    name: "Oregon CPA",\n'
    '    statute: "ORS \u00a7\u00a7 646A.570\u2013646A.604",\n'
    '    lawUrl: "https://www.oregonlegislature.gov/bills_laws/ors/ors646A.html",\n'
    '    lawLinkText: "Read ORS \u00a7\u00a7 646A.570 through 646A.604 on oregonlegislature.gov",\n'
    '    acknowledgment:\n'
    '      "I have reviewed ORS \u00a7\u00a7 646A.570 through 646A.604 (Oregon Consumer Privacy Act) and understand that these are compliance templates, not legal advice. The Oregon CPA has been in effect since July 1, 2024, with the cure period expiring January 1, 2026. I should verify the current regulatory status and consult qualified legal counsel.",\n'
    '    basePrice: 249,\n'
    '    trainingKitAvailable: false,\n'
    '    trainingKitPrice: 0,\n'
    '    documents: [\n'
    '      "Privacy Notice Template",\n'
    '      "Data Protection Assessment",\n'
    '      "Consumer Rights Request Procedures",\n'
    '      "Profiling Opt-Out Documentation",\n'
    '      "Data Processing Agreement Template",\n'
    '      "Compliance Checklist",\n'
    '    ],\n'
    '    decisions: [\n'
    '      ["profiling", "Profiling/Automated Decisions"],\n'
    '      ["targeted_ads", "Targeted Advertising"],\n'
    '      ["data_sales", "Data Sales"],\n'
    '      ["sensitive_data", "Sensitive Data Processing"],\n'
    "      [\"children_data\", \"Children's Data (ages 13\u201315)\"],\n"
    '    ],\n'
    '    helpTexts: {\n'
    '      step2Help:\n'
    '        "<strong>What AI systems are covered?</strong> Any system that uses personal data of Oregon consumers for profiling, targeted advertising, data sales, or processing sensitive data. Oregon also requires consent before processing data of consumers aged 13\u201315 for targeted advertising or data sales. If your AI system makes decisions about consumers \u2014 include it.",\n'
    '      step2Intro:\n'
    '        "List each AI or data processing system used in activities covered by the Oregon Consumer Privacy Act.",\n'
    '      step2DecisionHelp:\n'
    '        "Check every category where this system processes Oregon consumer data. The Oregon CPA covers profiling for consequential decisions, targeted advertising, data sales, sensitive data, and has special protections for consumers aged 13\u201315.",\n'
    '      step2MultiHelp:\n'
    '        "If you use multiple systems across these categories, list each separately. Each may require its own data protection assessment.",\n'
    '      step3BiasHelp:\n'
    '        "If your system uses profiling to make decisions with legal or similarly significant effects, a bias review helps document that your processing does not produce unfair or discriminatory outcomes.",\n'
    '      step4Help:\n'
    '        "This section captures your oversight and governance for data processing activities. Oregon law requires responding to consumer rights requests within 45 days. The 30-day cure period expires January 1, 2026 \u2014 after that date, the AG has enforcement discretion.",\n'
    '      step5Intro:\n'
    '        "This contact will be listed in your privacy notices and consumer rights procedures as the designated privacy contact under the Oregon Consumer Privacy Act.",\n'
    '    },\n'
    '  },\n'
)

target = '  "minnesota-mcdpa": {'
if target in content:
    content = content.replace(target, new_configs + target, 1)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print('SUCCESS: inserted 3 regulation configs before minnesota-mcdpa')
else:
    print('ERROR: target not found')
    sys.exit(1)
