import { jsPDF } from "jspdf";
import type { ComplianceFormData } from "../pdf-types";
import {
  addDocHeader,
  addTopDisclaimer,
  addSectionHeader,
  addWrappedText,
  addFormTextField,
  addFormCheckbox,
  addDisclaimer,
  addSignatureBlock,
  MARGIN,
  CONTENT_WIDTH,
  LINE_HEIGHT,
} from "../pdf-helpers";

// ============================================================
// DOCUMENT 5: Vendor AI Due Diligence — Financial Services
// FINRA Rule 3110 + FINRA RN 24-09 + SR 11-7 Model Risk
// ============================================================
export function generateVendorDueDiligenceFinancial(data: ComplianceFormData): jsPDF {
  const doc = new jsPDF();
  let y = addDocHeader(doc, "AI Vendor Due Diligence Questionnaire — Financial Services", data);
  y = addTopDisclaimer(doc, y);

  y = addWrappedText(
    doc,
    `This vendor due diligence questionnaire is completed by ${data.company.name} for each AI vendor whose tools are used in securities, lending, or financial services activities. FINRA Rule 3110 supervisory obligations extend to AI tools provided by third-party vendors. FINRA Regulatory Notice 24-09 affirms that the use of third-party AI tools does not relieve member firms of their supervisory responsibilities. This questionnaire supports SR 11-7 model risk management for third-party models.`,
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT;

  // Vendor Information
  y = addSectionHeader(doc, "1. Vendor Identification", y);
  y = addFormTextField(doc, "vendor_name", "AI Vendor Name:", y, { width: 140 });
  y = addFormTextField(doc, "vendor_address", "Vendor Address:", y, { width: 140 });
  y = addFormTextField(doc, "vendor_website", "Vendor Website:", y, { width: 120 });
  y = addFormTextField(doc, "vendor_contact_name", "Vendor Primary Contact Name:", y, { width: 120 });
  y = addFormTextField(doc, "vendor_contact_email", "Vendor Contact Email:", y, { width: 120 });
  y = addFormTextField(doc, "vendor_contact_phone", "Vendor Contact Phone:", y, { width: 80 });
  y = addFormTextField(doc, "ai_product_name", "AI Product/Service Name:", y, { width: 140 });
  y = addFormTextField(doc, "ai_product_version", "Current Version/Release:", y, { width: 80 });
  y = addFormTextField(doc, "contract_date", "Contract Effective Date:", y, { width: 80 });
  y += LINE_HEIGHT;

  // Section 2: Regulatory and Compliance Status
  y = addSectionHeader(doc, "2. Regulatory and Compliance Status", y);
  const regItems = [
    "Vendor has assessed whether its AI tool is subject to FINRA, SEC, CFPB, or other financial services regulatory requirements",
    "Vendor can demonstrate that AI tool supports firm's compliance with FINRA Rule 3110 supervisory obligations",
    "Vendor can provide audit-ready documentation of model development, testing, and validation (SR 11-7)",
    "Vendor has conducted disparate impact testing for AI tools used in credit decisions",
    "Vendor can produce specific, human-understandable reasons for adverse credit decisions generated by AI (ECOA/Reg B compliance)",
    "Vendor complies with FCRA when consumer report data is processed (15 U.S.C. \u00A7 1681 et seq.)",
    "Vendor has data privacy program compliant with applicable law (CCPA, state privacy laws)",
    "Vendor maintains professional liability / errors and omissions insurance",
  ];
  let cbIdx = 0;
  regItems.forEach((item) => {
    y = addFormCheckbox(doc, `reg_${cbIdx}`, item, y);
    cbIdx++;
  });
  y += LINE_HEIGHT;

  // Section 3: Model Risk (SR 11-7 / OCC 2011-12)
  y = addSectionHeader(doc, "3. Model Risk Documentation (SR 11-7)", y);
  const modelItems = [
    "Vendor provides model documentation including conceptual soundness, development methodology, and assumptions",
    "Vendor provides model validation reports from independent validation team",
    "Vendor documents model performance metrics (precision, recall, AUC) and provides updates when models are retrained",
    "Vendor discloses training data sources, date range, and geographic coverage",
    "Vendor performs and discloses results of ongoing model performance monitoring",
    "Vendor provides advance notice before making material changes to model (minimum 30 days requested)",
    "Vendor provides documentation of any known model limitations or failure modes",
    "Vendor discloses all sub-processors and third-party model components",
  ];
  modelItems.forEach((item) => {
    y = addFormCheckbox(doc, `model_${cbIdx}`, item, y);
    cbIdx++;
  });
  y += LINE_HEIGHT;

  // Section 4: Security and Data Governance
  y = addSectionHeader(doc, "4. Security and Data Governance", y);
  const secItems = [
    "Vendor maintains SOC 2 Type II (or equivalent) and provides current report upon request",
    "Vendor has documented data retention and deletion policies; does not retain firm customer data beyond contract term",
    "Vendor prohibits use of firm customer data for AI model training without explicit written authorization",
    "Vendor discloses all jurisdictions where firm data is stored and processed",
    "Vendor has documented breach notification procedures with notification timeline of no more than 72 hours",
    "Vendor undergoes annual penetration testing and shares executive summary with firm upon request",
    "Vendor encrypts data in transit and at rest",
    "Vendor maintains audit logs of all data access events",
  ];
  secItems.forEach((item) => {
    y = addFormCheckbox(doc, `sec_${cbIdx}`, item, y);
    cbIdx++;
  });
  y += LINE_HEIGHT;

  // Section 5: FINRA Rule 3110 Supervisory Controls
  y = addSectionHeader(doc, "5. Supervisory Control Requirements (FINRA Rule 3110 + FINRA RN 24-09)", y);
  const supItems = [
    "Firm retains ability to supervise and override AI tool outputs (firm does not delegate supervisory function to vendor)",
    "Vendor provides usage logs sufficient for firm's supervisory reviews",
    "Vendor supports firm's ability to produce records required by FINRA Rule 4511",
    "Vendor agrees to cooperate with regulatory examinations related to its AI tool",
    "Vendor provides training resources for firm personnel on AI tool capabilities and limitations",
    "Vendor maintains service level agreements with defined uptime and incident response timelines",
    "Contract includes firm's right to terminate if vendor cannot cure compliance deficiencies within 30 days",
  ];
  supItems.forEach((item) => {
    y = addFormCheckbox(doc, `sup_${cbIdx}`, item, y);
    cbIdx++;
  });
  y += LINE_HEIGHT;

  // Section 6: Adverse Action Specific
  y = addSectionHeader(doc, "6. Adverse Action Reason Requirement (ECOA/Regulation B)", y);
  y = addWrappedText(
    doc,
    "Complete this section only for AI tools used in credit decisions subject to ECOA/Regulation B.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 4;
  const aaItems = [
    "Vendor confirms AI tool can produce specific, human-understandable principal reasons for adverse credit decisions",
    "Vendor confirms adverse action reasons accurately reflect actual model factors (not generic codes unrelated to model logic)",
    "Vendor provides documentation mapping model outputs to adverse action reason codes",
    "Firm has tested vendor's adverse action reason output for accuracy and ECOA compliance",
    "Vendor provides updated adverse action reason mapping when model is retrained",
  ];
  aaItems.forEach((item) => {
    y = addFormCheckbox(doc, `aa_${cbIdx}`, item, y);
    cbIdx++;
  });
  y += LINE_HEIGHT;

  // Findings and Approval
  y = addSectionHeader(doc, "7. Due Diligence Findings and Approval", y);
  y = addFormTextField(doc, "findings", "Key Findings:", y, { multiline: true, lines: 4 });
  y = addFormTextField(doc, "risks", "Identified Risks:", y, { multiline: true, lines: 3 });
  y = addFormTextField(doc, "mitigations", "Required Mitigations:", y, { multiline: true, lines: 3 });
  y = addFormTextField(doc, "dd_decision", "Due Diligence Decision (Approve / Approve with Conditions / Reject):", y, { width: 120 });
  y = addFormTextField(doc, "dd_approved_by", "Approved by (Compliance Officer/Principal):", y, { width: 120 });
  y = addFormTextField(doc, "dd_crd", "CRD Number:", y, { width: 60 });
  y = addFormTextField(doc, "dd_date", "Date:", y, { width: 60 });
  y = addFormTextField(doc, "dd_next_review", "Next Annual Review Date:", y, { width: 60 });

  if (y > 240) { doc.addPage(); y = 20; }
  y = addSignatureBlock(doc, "fin_vdd", y);

  addDisclaimer(doc);
  return doc;
}
