import { jsPDF } from "jspdf";
import type { ComplianceFormData } from "../pdf-types";
import {
  addDocHeader,
  addTopDisclaimer,
  addSectionHeader,
  addWrappedText,
  addFormTextField,
  addFormCheckbox,
  addDisclaimer,
  addSignatureBlock,
  MARGIN,
  CONTENT_WIDTH,
  LINE_HEIGHT,
} from "../pdf-helpers";

// ============================================================
// DOCUMENT 3: Log Retention Policy
// EU AI Act Art. 26(6) — Deployer log retention
// ============================================================
export function generateLogRetentionPolicy(data: ComplianceFormData): jsPDF {
  const doc = new jsPDF();
  let y = addDocHeader(
    doc,
    "EU AI Act: Log Retention Policy (Art. 26(6))",
    data
  );
  y = addTopDisclaimer(doc, y);

  y = addWrappedText(
    doc,
    `This Log Retention Policy is established by ${data.company.name} pursuant to Article 26(6) of Regulation (EU) 2024/1689 (EU AI Act). Article 26(6) requires deployers to retain automatically generated logs from high-risk AI systems for a minimum of six months, unless longer retention is required by applicable EU or Member State law or by other legal obligations. This policy documents the organization's log retention practices and must be maintained current and made available to the competent authority upon request.`,
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT;

  // AI system identification
  y = addSectionHeader(doc, "1. AI System Identification", y);
  y = addFormTextField(doc, "logreten_sys_name", "AI system name:", y, { width: 140 });
  y = addFormTextField(doc, "logreten_sys_version", "Version / build:", y, { width: 80 });
  y = addFormTextField(doc, "logreten_sys_provider", "Provider name:", y, { width: 140 });
  y = addFormTextField(doc, "logreten_policy_date", "Policy effective date:", y, { width: 80 });
  y = addFormTextField(doc, "logreten_policy_owner", "Policy owner (name, title):", y, { width: 140 });
  y += LINE_HEIGHT;

  // Section 1: What logs are retained
  y = addSectionHeader(doc, "2. What Logs Are Retained (Art. 26(6))", y);
  y = addWrappedText(
    doc,
    "Article 26(6) specifies that deployers retain the automatically generated logs produced by the AI system to the extent these are under their control. Describe below the categories of logs generated by this AI system and retained under this policy.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 4;

  const logCategories = [
    "Automatic event logs generated by the AI system during operation (per Art. 12 / Art. 26(6))",
    "Input data records (data submitted to the AI system for each transaction)",
    "Output records (decisions, scores, recommendations generated by the system)",
    "Human oversight actions and override records",
    "System access logs (who accessed the system and when)",
    "Configuration and parameter change logs",
    "Error and exception logs",
    "Performance and monitoring metric logs",
  ];
  logCategories.forEach((cat, idx) => {
    y = addFormCheckbox(doc, `logreten_cat_${idx}`, cat, y);
  });
  y = addFormTextField(
    doc,
    "logreten_cat_other",
    "Other log categories retained under this policy:",
    y,
    { multiline: true, lines: 2 }
  );
  y = addFormTextField(
    doc,
    "logreten_cat_not_controlled",
    "Logs generated by the AI system but NOT under deployer's control (explain):",
    y,
    { multiline: true, lines: 2 }
  );
  y += LINE_HEIGHT;

  // Section 2: Retention period
  y = addSectionHeader(doc, "3. Retention Period (Art. 26(6) Minimum: 6 Months)", y);
  y = addWrappedText(
    doc,
    "Article 26(6) establishes a minimum retention period of six months for automatically generated logs, unless a longer period is required by applicable EU or Member State law. State the retention period applied under this policy and the legal basis for any period exceeding the minimum.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 4;

  const retentionPeriods = [
    "6 months — statutory minimum per Art. 26(6)",
    "12 months — extended to align with annual review cycle",
    "24 months — extended by [specify applicable law below]",
    "36 months — extended by [specify applicable law below]",
    "Other retention period — specify below",
  ];
  retentionPeriods.forEach((period, idx) => {
    y = addFormCheckbox(doc, `logreten_period_${idx}`, period, y);
  });
  y = addFormTextField(
    doc,
    "logreten_period_basis",
    "Legal basis for retention period if longer than 6 months (cite applicable EU law, Member State law, or other obligation):",
    y,
    { multiline: true, lines: 3 }
  );
  y = addFormTextField(
    doc,
    "logreten_period_start",
    "Retention period starts from: (e.g., date of each log entry, date of end of AI system deployment):",
    y,
    { multiline: true, lines: 2 }
  );
  y += LINE_HEIGHT;

  // Section 3: Storage location
  y = addSectionHeader(doc, "4. Storage Location", y);
  y = addFormTextField(
    doc,
    "logreten_storage_system",
    "Storage system name and type (e.g., cloud storage, on-premises server, SIEM platform):",
    y,
    { multiline: true, lines: 2 }
  );
  y = addFormTextField(
    doc,
    "logreten_storage_location",
    "Physical or geographic location of storage (including data residency / Member State):",
    y,
    { multiline: true, lines: 2 }
  );
  y = addFormTextField(
    doc,
    "logreten_storage_backup",
    "Backup arrangements (frequency, location, recovery tested):",
    y,
    { multiline: true, lines: 2 }
  );
  y += LINE_HEIGHT;

  // Section 4: Access controls
  y = addSectionHeader(doc, "5. Access Controls", y);
  y = addWrappedText(
    doc,
    "Describe who has access to retained logs and the controls preventing unauthorized access, modification, or deletion.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 4;
  y = addFormTextField(
    doc,
    "logreten_access_authorized",
    "Personnel authorized to access logs (roles, not names):",
    y,
    { multiline: true, lines: 2 }
  );
  y = addFormTextField(
    doc,
    "logreten_access_controls",
    "Technical access controls in place (e.g., role-based access, MFA, audit trail of access):",
    y,
    { multiline: true, lines: 3 }
  );
  y = addFormTextField(
    doc,
    "logreten_access_authority",
    "Process for providing log access to competent authority upon request:",
    y,
    { multiline: true, lines: 2 }
  );
  y += LINE_HEIGHT;

  // Section 5: Deletion procedures
  y = addSectionHeader(doc, "6. Deletion Procedures", y);
  y = addWrappedText(
    doc,
    "Describe how logs are deleted after the retention period expires. Deletion must be secure and verifiable. Note any legal holds that may extend retention beyond the standard period.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 4;
  y = addFormTextField(
    doc,
    "logreten_delete_method",
    "Deletion method (secure deletion standard applied):",
    y,
    { multiline: true, lines: 2 }
  );
  y = addFormTextField(
    doc,
    "logreten_delete_trigger",
    "How deletion is triggered (automated, manual review, calendar-based):",
    y,
    { multiline: true, lines: 2 }
  );
  y = addFormTextField(
    doc,
    "logreten_delete_legal_hold",
    "Legal hold procedures — how deletion is suspended when legal proceedings, regulatory investigations, or litigation hold applies:",
    y,
    { multiline: true, lines: 3 }
  );
  y += LINE_HEIGHT;

  // Section 6: Chain of custody documentation
  y = addSectionHeader(doc, "7. Chain of Custody Documentation", y);
  y = addWrappedText(
    doc,
    "Documenting chain of custody ensures logs are admissible and credible if used in regulatory proceedings or legal disputes. Describe the custody documentation maintained for retained logs.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 4;
  y = addFormTextField(
    doc,
    "logreten_custody_record",
    "How chain of custody is documented (access logs, hash verification, change logs):",
    y,
    { multiline: true, lines: 3 }
  );
  y = addFormTextField(
    doc,
    "logreten_custody_integrity",
    "How log integrity is verified (cryptographic hashing, write-once storage, audit trail):",
    y,
    { multiline: true, lines: 2 }
  );
  y = addFormTextField(
    doc,
    "logreten_custody_incidents",
    "Process for documenting and reporting unauthorized access, modification, or deletion of logs:",
    y,
    { multiline: true, lines: 2 }
  );
  y += LINE_HEIGHT;

  if (y > 240) {
    doc.addPage();
    y = 20;
  }
  y = addSignatureBlock(doc, "logreten_sign", y);

  addDisclaimer(doc);
  return doc;
}
