import { jsPDF } from "jspdf";
import type { ComplianceFormData } from "../pdf-types";
import {
  MARGIN,
  CONTENT_WIDTH,
  LINE_HEIGHT,
  addDocHeader,
  addTopDisclaimer,
  addSectionHeader,
  addWrappedText,
  addFormTextField,
  addFormCheckbox,
  addDisclaimer,
} from "../pdf-helpers";

// ============================================================
// DOCUMENT 1: Personal Data Inventory
// What data, why, where, how long
// ============================================================
export function generateDataInventory(data: ComplianceFormData): jsPDF {
  const doc = new jsPDF();
  let y = addDocHeader(doc, "Personal Data Inventory", data);
  y = addTopDisclaimer(doc, y);

  y = addWrappedText(
    doc,
    "This inventory documents the personal data collected and processed by " +
      data.company.name +
      ". " +
      "A current data inventory is a prerequisite for data protection assessments required by CA CCPA, CO SB24-205, MN MCDPA, TX TDPSA, DE PDPA, and other state privacy laws. " +
      "Update this inventory whenever new data types, systems, or processing activities are added.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT;

  // ── Inventory Metadata ─────────────────────────────────────
  y = addSectionHeader(doc, "Inventory Metadata", y);
  y = addFormTextField(doc, "di_as_of_date", "Inventory As Of:", y);
  y = addFormTextField(doc, "di_owner", "Data Inventory Owner (Name, Title):", y);
  y = addFormTextField(doc, "di_last_reviewed", "Last Full Review Date:", y);
  y = addFormTextField(doc, "di_next_review", "Next Scheduled Review:", y);
  y += LINE_HEIGHT;

  // ── Section 1: Data Categories Collected ──────────────────
  y = addSectionHeader(doc, "1. Data Categories Collected", y);
  y = addWrappedText(
    doc,
    "Check all categories of personal data collected by your organization:",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT / 2;

  const dataCategories = [
    { name: "di_cat_name", label: "Identifiers (name, email, phone, address, IP address, account IDs)" },
    { name: "di_cat_financial", label: "Financial information (account numbers, credit scores, income, payment history)" },
    { name: "di_cat_health", label: "Health / medical information (diagnoses, medications, insurance)" },
    { name: "di_cat_biometric", label: "Biometric data (fingerprints, voiceprints, face geometry, retina scans)" },
    { name: "di_cat_location", label: "Geolocation data (precise location, travel patterns)" },
    { name: "di_cat_behavioral", label: "Behavioral / browsing data (clicks, searches, purchase history, preferences)" },
    { name: "di_cat_employment", label: "Employment data (performance records, salary, hiring/discipline records)" },
    { name: "di_cat_education", label: "Education records (grades, transcripts, enrollment)" },
    { name: "di_cat_racial", label: "Racial or ethnic origin" },
    { name: "di_cat_political", label: "Political opinions, religious beliefs, union membership" },
    { name: "di_cat_sexual", label: "Sexual orientation, gender identity" },
    { name: "di_cat_communications", label: "Contents of communications (emails, messages, call recordings)" },
    { name: "di_cat_inferred", label: "Inferred data (profiles, scores, predictions generated by AI)" },
    { name: "di_cat_children", label: "Children's data (persons under 13 / under 16 in some states)" },
    { name: "di_cat_credentials", label: "Login credentials (usernames, passwords, security questions)" },
  ];
  dataCategories.forEach((cat) => {
    if (y > 255) { doc.addPage(); y = MARGIN; }
    y = addFormCheckbox(doc, cat.name, cat.label, y);
    y += 1;
  });
  y += LINE_HEIGHT;

  // ── Section 2: Data Inventory Table ───────────────────────
  if (y > 180) { doc.addPage(); y = MARGIN; }
  y = addSectionHeader(doc, "2. Data Inventory — System-by-System", y);
  y = addWrappedText(
    doc,
    "Complete one entry for each system or process that collects or uses personal data. " +
      "This is the core of your data map — required before any data protection assessment.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT;

  // Draw inventory entry template (3 entries)
  for (let entry = 1; entry <= 4; entry++) {
    if (y > 180) { doc.addPage(); y = MARGIN; }

    // Entry header
    doc.setFillColor(235, 240, 250);
    doc.setDrawColor(50, 100, 200);
    doc.setLineWidth(0.5);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 7, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(30, 60, 130);
    doc.text("Data Processing Activity #" + entry, MARGIN + 3, y + 5);
    doc.setTextColor(0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y += 9;

    const prefix = "di_entry" + entry + "_";
    y = addFormTextField(doc, prefix + "name", "System / Process Name:", y);
    y = addFormTextField(doc, prefix + "purpose", "Purpose of Processing:", y, { multiline: true, lines: 2 });
    y = addFormTextField(doc, prefix + "data_types", "Data Types Processed:", y, { multiline: true, lines: 2 });
    y = addFormTextField(doc, prefix + "source", "Data Source (how collected):", y, { multiline: true, lines: 2 });
    y = addFormTextField(doc, prefix + "legal_basis", "Legal Basis for Processing:", y, { multiline: true, lines: 2 });
    y = addFormTextField(doc, prefix + "retention", "Retention Period:", y);
    y = addFormTextField(doc, prefix + "shared_with", "Shared With (third parties, processors):", y, { multiline: true, lines: 2 });
    y = addFormTextField(doc, prefix + "ai_use", "Does AI process this data? If yes, describe:", y, { multiline: true, lines: 2 });
    y = addFormTextField(doc, prefix + "high_risk", "Heightened risk? (profiling, decisions, sensitive data):", y);
    y += LINE_HEIGHT;
  }

  // ── Section 3: Data Subject Population ────────────────────
  if (y > 200) { doc.addPage(); y = MARGIN; }
  y = addSectionHeader(doc, "3. Data Subject Populations", y);
  const populations = [
    { name: "di_pop_customers", label: "Customers / Consumers" },
    { name: "di_pop_employees", label: "Employees / Job Applicants" },
    { name: "di_pop_contractors", label: "Contractors / Vendors" },
    { name: "di_pop_minors", label: "Minors (under 16)" },
    { name: "di_pop_website", label: "Website Visitors" },
    { name: "di_pop_eu", label: "EU Residents (EU AI Act / GDPR applies)" },
  ];
  populations.forEach((pop) => {
    y = addFormCheckbox(doc, pop.name, pop.label, y);
    y += 1;
  });
  y += LINE_HEIGHT;

  // ── Section 4: High-Risk Processing Summary ────────────────
  y = addSectionHeader(doc, "4. High-Risk Processing Summary", y);
  y = addWrappedText(
    doc,
    "Identify all processing activities that require a data protection assessment under applicable law:",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT / 2;

  const highRisk = [
    { name: "di_hr_profiling", label: "Profiling with legal or similarly significant effects" },
    { name: "di_hr_admt", label: "Automated decision-making without human review" },
    { name: "di_hr_sensitive", label: "Large-scale processing of sensitive categories" },
    { name: "di_hr_surveillance", label: "Systematic monitoring of a publicly accessible area" },
    { name: "di_hr_children", label: "Processing personal data of minors" },
    { name: "di_hr_biometric", label: "Biometric data for identification purposes" },
    { name: "di_hr_location", label: "Large-scale processing of precise geolocation data" },
  ];
  highRisk.forEach((item) => {
    y = addFormCheckbox(doc, item.name, item.label, y);
    y += 1;
  });
  y += LINE_HEIGHT;

  // ── Certification ──────────────────────────────────────────
  if (y > 230) { doc.addPage(); y = MARGIN; }
  y = addSectionHeader(doc, "Inventory Certification", y);
  y = addFormTextField(doc, "di_cert_name", "Certified By (Name, Title):", y);
  y = addFormTextField(doc, "di_cert_sig", "Signature:", y);
  y = addFormTextField(doc, "di_cert_date", "Date:", y);

  addDisclaimer(doc);
  return doc;
}
