import { jsPDF } from "jspdf";
import type { ComplianceFormData } from "../pdf-types";
import {
  MARGIN,
  CONTENT_WIDTH,
  LINE_HEIGHT,
  addDocHeader,
  addTopDisclaimer,
  addSectionHeader,
  addWrappedText,
  addFormTextField,
  addDisclaimer,
} from "../pdf-helpers";

// ============================================================
// DOCUMENT 1: Customer AI Acceptable Use Policy
// Aligned with FTC Act § 5 + EU AI Act Art. 13 + Best Practice
// ============================================================
export function generateCustomerAUP(data: ComplianceFormData): jsPDF {
  const doc = new jsPDF();
  let y = addDocHeader(doc, "Customer AI Acceptable Use Policy", data);
  y = addTopDisclaimer(doc, y);

  // ── Introduction ───────────────────────────────────────────
  y = addSectionHeader(doc, "1. Introduction", y);
  y = addWrappedText(
    doc,
    "This Customer AI Acceptable Use Policy (\"Customer AUP\") governs the use of AI-powered " +
      "features, tools, and services provided by " + data.company.name + " (\"Company\") to " +
      "its customers (\"you\" or \"Customer\"). By accessing or using the Company's AI-powered " +
      "products or services, you agree to comply with this Customer AUP. This Policy is " +
      "separate from the Company's Employee AI Acceptable Use Policy, which governs internal " +
      "employee use of AI tools.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT;

  y = addFormTextField(doc, "caup_product_name", "AI Product / Service Name(s) Covered:", y, {
    multiline: true,
    lines: 2,
  });
  y = addFormTextField(doc, "caup_effective_date", "Policy Effective Date:", y);
  y += LINE_HEIGHT;

  // ── Definitions ────────────────────────────────────────────
  y = addSectionHeader(doc, "2. Definitions", y);
  const definitions = [
    '"AI Features" means any functionality within the Company\'s products or services ' +
      "that uses artificial intelligence, machine learning, natural language processing, " +
      "or automated decision-making, as disclosed in the applicable product documentation.",
    '"Customer Data" means any data, content, or information that you submit to or ' +
      "process through the AI Features, including but not limited to text inputs, uploaded " +
      "files, queries, and any data about your end users.",
    '"AI Output" means any content, analysis, recommendation, decision, or other output ' +
      "generated by the AI Features in response to Customer Data or queries.",
    '"Prohibited Use" means any use of the AI Features described in Section 4 of this Policy.',
    '"End Users" means individuals who access or interact with the AI Features through ' +
      "your account or your products, including your employees, contractors, and customers.",
  ];
  definitions.forEach((def) => {
    if (y > 265) {
      doc.addPage();
      y = MARGIN;
    }
    y = addWrappedText(doc, def, MARGIN + 3, y, CONTENT_WIDTH - 3, LINE_HEIGHT);
    y += 3;
  });
  y += LINE_HEIGHT;

  // ── Permitted Uses ─────────────────────────────────────────
  y = addSectionHeader(doc, "3. Permitted Uses", y);
  y = addWrappedText(
    doc,
    "You may use the AI Features only for lawful business purposes consistent with this " +
      "Customer AUP, your agreement with the Company, and applicable law. Permitted uses " +
      "include:",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 2;
  y = addFormTextField(
    doc,
    "caup_permitted_uses",
    "Permitted Use Cases (customize for your product):",
    y,
    { multiline: true, lines: 4 }
  );
  y += LINE_HEIGHT;

  // ── Prohibited Uses ────────────────────────────────────────
  y = addSectionHeader(doc, "4. Prohibited Uses", y);
  y = addWrappedText(
    doc,
    "You may not use the AI Features for any of the following prohibited purposes. " +
      "Violations may result in suspension or termination of your access to the AI Features.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 2;

  const prohibited = [
    "(a) Illegal or Harmful Activities: Using AI Features to engage in, facilitate, or " +
      "promote illegal activities, including but not limited to fraud, cybercrime, " +
      "money laundering, illegal drug trade, or human trafficking.",
    "(b) Discrimination: Using AI Features in ways that discriminate against individuals " +
      "based on race, color, national origin, sex, age, disability, religion, or other " +
      "protected characteristics in violation of applicable anti-discrimination laws, " +
      "including but not limited to the Fair Housing Act, Equal Credit Opportunity Act, " +
      "and Title VII.",
    "(c) Deception & Fraud: Using AI Features to generate or disseminate content that " +
      "is intentionally false or misleading, to impersonate individuals or organizations, " +
      "to create synthetic media designed to deceive, or to engage in phishing or social " +
      "engineering attacks.",
    "(d) Harm to Individuals: Using AI Features to harass, threaten, stalk, or otherwise " +
      "harm individuals; to create or distribute non-consensual intimate imagery; or to " +
      "generate content that incites violence.",
    "(e) Unauthorized Data Collection: Using AI Features to collect, harvest, or process " +
      "personal data without appropriate legal basis, consent, or privacy disclosures " +
      "required by applicable privacy law.",
    "(f) Security Circumvention: Using AI Features to reverse engineer, exploit, or " +
      "circumvent the Company's security controls, intellectual property protections, " +
      "or usage restrictions.",
    "(g) Competitive Intelligence Against Company: Using AI Features to systematically " +
      "extract or reproduce the Company's proprietary AI models, training data, or " +
      "intellectual property.",
    "(h) Autonomous High-Risk Decisions Without Human Review: Using AI Features to " +
      "make final autonomous decisions in high-stakes contexts — including medical " +
      "diagnosis, legal advice, financial decisions affecting individuals' access to " +
      "credit or services, or employment decisions — without appropriate human review " +
      "and oversight.",
    "(i) Violations of Third-Party Rights: Using AI Features to infringe third-party " +
      "intellectual property rights, violate confidentiality agreements, or process " +
      "third-party confidential data without authorization.",
  ];
  prohibited.forEach((item) => {
    if (y > 255) {
      doc.addPage();
      y = MARGIN;
    }
    y = addWrappedText(doc, item, MARGIN + 3, y, CONTENT_WIDTH - 3, LINE_HEIGHT);
    y += 4;
  });
  y += LINE_HEIGHT;

  // ── Data Handling ──────────────────────────────────────────
  y = addSectionHeader(doc, "5. Data Handling Obligations", y);
  const dataObs = [
    "5.1 Data Quality: You are responsible for ensuring that Customer Data submitted " +
      "to the AI Features is accurate, lawfully collected, and does not violate third-party " +
      "rights. The Company is not responsible for AI Outputs generated from inaccurate, " +
      "unlawfully collected, or third-party-infringing data.",
    "5.2 Sensitive Data: You must not submit sensitive personal data (including health " +
      "information, financial account numbers, government ID numbers, or biometric data) " +
      "to AI Features unless the applicable product documentation explicitly states that " +
      "the AI Feature is designed and approved for that data category.",
    "5.3 End User Notice: If you deploy AI Features to your end users, you are responsible " +
      "for providing appropriate notice and disclosures to your end users about AI use, " +
      "consistent with applicable law. The Company's Customer AUP does not substitute for " +
      "your obligations to your own end users.",
    "5.4 Data Retention: You are responsible for complying with applicable data retention " +
      "and deletion requirements for Customer Data. Consult the Company's Privacy Policy " +
      "and Data Processing Agreement for information about how the Company handles " +
      "Customer Data.",
  ];
  dataObs.forEach((item) => {
    if (y > 255) {
      doc.addPage();
      y = MARGIN;
    }
    y = addWrappedText(doc, item, MARGIN + 3, y, CONTENT_WIDTH - 3, LINE_HEIGHT);
    y += 4;
  });
  y += LINE_HEIGHT;

  // ── AI Output Limitations ──────────────────────────────────
  y = addSectionHeader(doc, "6. AI Output Limitations & Your Responsibilities", y);
  const limitations = [
    "AI Features are not infallible. AI Outputs may contain errors, omissions, or " +
      "inaccuracies. You are solely responsible for reviewing AI Outputs before acting " +
      "on them or sharing them with others.",
    "AI Features do not provide legal advice, medical advice, financial advice, or " +
      "other professional advice. AI Outputs are informational only and must be reviewed " +
      "by qualified professionals before being used for professional purposes.",
    "You may not represent AI Outputs as having been independently verified unless " +
      "you have in fact verified them.",
    "You are responsible for the acts and omissions of your End Users in connection " +
      "with their use of the AI Features through your account.",
  ];
  limitations.forEach((item) => {
    if (y > 265) {
      doc.addPage();
      y = MARGIN;
    }
    y = addWrappedText(doc, "\u2022  " + item, MARGIN + 3, y, CONTENT_WIDTH - 3, LINE_HEIGHT);
    y += 4;
  });
  y += LINE_HEIGHT;

  // ── Enforcement ────────────────────────────────────────────
  y = addSectionHeader(doc, "7. Enforcement", y);
  y = addWrappedText(
    doc,
    "The Company reserves the right to investigate suspected violations of this Customer AUP. " +
      "If the Company determines that you have violated this Policy, the Company may, at its " +
      "discretion: (a) issue a warning; (b) temporarily suspend your access to AI Features; " +
      "(c) permanently terminate your access to AI Features; or (d) take legal action to " +
      "address damages or ongoing violations. Violations that create legal liability for the " +
      "Company or harm to third parties may be reported to appropriate law enforcement " +
      "or regulatory authorities.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT;

  // ── Violations Reporting ───────────────────────────────────
  y = addSectionHeader(doc, "8. Reporting Violations", y);
  y = addWrappedText(
    doc,
    "If you observe or suspect a violation of this Customer AUP — including misuse of " +
      "AI Features by another customer or by your own end users — please report it to:",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT;

  y = addFormTextField(doc, "caup_violations_contact", "AUP Violations Contact (Email / Portal):", y);
  y += LINE_HEIGHT;

  // ── Policy Updates ─────────────────────────────────────────
  y = addSectionHeader(doc, "9. Policy Updates", y);
  y = addWrappedText(
    doc,
    "The Company may update this Customer AUP at any time to reflect changes in AI " +
      "Features, applicable law, or best practices. Material changes will be communicated " +
      "to customers in advance. Continued use of AI Features after the effective date of " +
      "an updated Customer AUP constitutes acceptance of the updated terms.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT;

  // ── Contact ────────────────────────────────────────────────
  y = addSectionHeader(doc, "10. Contact Information", y);
  y = addFormTextField(doc, "caup_company_name", "Company Name:", y, {
    prefill: data.company.name,
    readOnly: false,
  });
  y = addFormTextField(doc, "caup_company_address", "Company Address:", y);
  y = addFormTextField(doc, "caup_company_email", "AI Policy Contact Email:", y);

  addDisclaimer(doc);
  return doc;
}
