import { jsPDF } from "jspdf";
import type { ComplianceFormData } from "../pdf-types";
import {
  addDocHeader,
  addTopDisclaimer,
  addSectionHeader,
  addWrappedText,
  addFormTextField,
  addFormCheckbox,
  addDisclaimer,
  addSignatureBlock,
  MARGIN,
  CONTENT_WIDTH,
  LINE_HEIGHT,
} from "../pdf-helpers";

// ============================================================
// Sensitive Data Consent Documentation
// Virginia CDPA — Va. Code § 59.1-578(A)(5)
// ============================================================
export function generateSensitiveDataConsent(
  data: ComplianceFormData
): jsPDF {
  const doc = new jsPDF();
  let y = addDocHeader(
    doc,
    "Sensitive Data Processing — Consent Documentation",
    data
  );
  y = addTopDisclaimer(doc, y);

  y = addWrappedText(
    doc,
    `This document records the basis of consent obtained by ${data.company.name} for processing sensitive data under the Virginia Consumer Data Protection Act (VCDPA), Va. Code § 59.1-578(A)(5). The VCDPA prohibits processing sensitive data without the consumer's consent (§ 59.1-578(A)(5)), except in limited circumstances set out in § 59.1-578(B). "Sensitive data" is defined in § 59.1-575 and includes the categories enumerated below. Consent must be a clear affirmative act freely given, specific, informed, and unambiguous (§ 59.1-575).`,
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += LINE_HEIGHT;

  // ── Section 1: Identity of Consumer and Controller ────────
  y = addSectionHeader(
    doc,
    "Section 1 — Consumer & Controller Identification",
    y
  );
  y = addFormTextField(doc, "sdc_consumer_name", "Consumer Full Name:", y);
  y = addFormTextField(doc, "sdc_consumer_id", "Consumer Account ID / Identifier:", y);
  y = addFormTextField(
    doc,
    "sdc_controller_name",
    "Controller / Business Name:",
    y,
    { prefill: data.company.name }
  );
  y = addFormTextField(doc, "sdc_consent_date", "Date Consent Obtained:", y);
  y += 4;

  // ── Section 2: Categories of Sensitive Data Being Processed ──
  y = addSectionHeader(
    doc,
    "Section 2 — Sensitive Data Categories Being Processed (§ 59.1-575)",
    y
  );
  y = addWrappedText(
    doc,
    "Check each category of sensitive data for which consent is being documented. Per § 59.1-575, sensitive data includes:",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  const sensitiveCategories = [
    "Racial or ethnic origin",
    "Religious beliefs",
    "Mental or physical health diagnosis",
    "Sexual orientation or gender identity",
    "Immigration or citizenship status",
    "Genetic data (data resulting from specific technical processing relating to the physical, physiological, or behavioral characteristics of a natural person)",
    "Biometric data (data generated by automatic measurements of biological characteristics — used to uniquely identify a consumer)",
    "Precise geolocation data (location data within a 1,750 foot radius)",
    "Personal data of a known child (consumer under 13) — subject to Children's Online Privacy Protection Act (COPPA) in addition to VCDPA",
    "Financial data, including bank account numbers and payment card numbers",
    "Passwords and account credentials",
    "Other sensitive data not listed above (describe below)",
  ];
  sensitiveCategories.forEach((cat, catIdx) => {
    y = addFormCheckbox(doc, `sdc_category_${catIdx}`, cat, y);
  });
  y = addFormTextField(
    doc,
    "sdc_category_other",
    "Other sensitive data description:",
    y,
    { multiline: true, lines: 2 }
  );
  y += 4;

  // ── Section 3: Purpose of Processing ─────────────────────
  y = addSectionHeader(doc, "Section 3 — Purpose of Processing", y);
  y = addFormTextField(
    doc,
    "sdc_purpose",
    "Specific, explicit purpose(s) for which sensitive data is being processed:",
    y,
    { multiline: true, lines: 4 }
  );
  y = addFormTextField(
    doc,
    "sdc_necessity",
    "Why is it necessary to process sensitive data to achieve this purpose (rather than non-sensitive data)?",
    y,
    { multiline: true, lines: 3 }
  );
  y += 4;

  // ── Section 4: Consent Mechanism ─────────────────────────
  y = addSectionHeader(
    doc,
    "Section 4 — Consent Mechanism (§ 59.1-575 — must be clear affirmative act, freely given, specific, informed, unambiguous)",
    y
  );
  y = addWrappedText(
    doc,
    "Consent mechanism used — check the applicable method:",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  const consentMechanisms = [
    "Written consent form (signed physical or electronic document)",
    "Opt-in checkbox (unchecked by default) on account registration or settings page",
    "Opt-in checkbox within a standalone sensitive data consent notice",
    "In-app or in-product consent flow with affirmative 'I agree' button",
    "Verbal consent with recorded confirmation (describe below)",
    "Other consent mechanism (describe below)",
  ];
  consentMechanisms.forEach((mech, mechIdx) => {
    y = addFormCheckbox(doc, `sdc_mechanism_${mechIdx}`, mech, y);
  });
  y = addFormTextField(
    doc,
    "sdc_mechanism_description",
    "Consent mechanism description (required if 'Verbal' or 'Other' selected above):",
    y,
    { multiline: true, lines: 2 }
  );
  y = addFormTextField(
    doc,
    "sdc_consent_record_location",
    "Location where consent record is stored (system / database / file):",
    y
  );
  y += 4;

  // ── Section 5: Withdrawal Mechanism ──────────────────────
  y = addSectionHeader(
    doc,
    "Section 5 — Consent Withdrawal Mechanism (§ 59.1-578(A)(5))",
    y
  );
  y = addWrappedText(
    doc,
    "Consumers must be able to withdraw consent as easily as it was given. Describe the withdrawal mechanism provided:",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 2;
  y = addFormTextField(
    doc,
    "sdc_withdrawal_method",
    "Withdrawal mechanism (e.g., account settings toggle, email request, in-app control):",
    y,
    { multiline: true, lines: 3 }
  );
  y = addFormTextField(
    doc,
    "sdc_withdrawal_effect",
    "Effect of withdrawal — what processing ceases and within what timeframe:",
    y,
    { multiline: true, lines: 2 }
  );
  y = addFormTextField(
    doc,
    "sdc_withdrawal_date",
    "Date consent was withdrawn (if applicable):",
    y
  );
  y += 4;

  // ── Section 6: Children's Data Special Provisions ────────
  y = addSectionHeader(
    doc,
    "Section 6 — Children's Data — Special Provisions (if applicable)",
    y
  );
  y = addFormCheckbox(
    doc,
    "sdc_children_data",
    "This consent record covers personal data of a known child (consumer under 13)",
    y
  );
  y = addWrappedText(
    doc,
    "If the above box is checked: COPPA (15 U.S.C. § 6501 et seq.) requires verifiable parental consent before collecting, using, or disclosing personal information from children under 13. VCDPA § 59.1-578(B)(4) does not override COPPA. Ensure a separate COPPA-compliant consent process is followed and documented.",
    MARGIN,
    y,
    CONTENT_WIDTH,
    LINE_HEIGHT
  );
  y += 2;
  y = addFormTextField(
    doc,
    "sdc_children_parent_consent",
    "Parental / guardian consent obtained from (name, if applicable):",
    y
  );
  y = addFormTextField(
    doc,
    "sdc_children_coppa_notes",
    "COPPA compliance notes:",
    y,
    { multiline: true, lines: 2 }
  );
  y += LINE_HEIGHT;

  if (y > 240) { doc.addPage(); y = 20; }
  y = addSignatureBlock(doc, "sdc", y);

  addDisclaimer(doc);
  return doc;
}
